get http://localhost:3001/BadRequest
### 
get http://localhost:3001/info
###
get http://localhost:3001/api/persons
###
@id = 1
get http://localhost:3001/api/persons/{{id}}
###
delete url HTTP/1.1 http://localhost:3001/api/persons/{{id}}